// Hamur Evi - Tam Menü Verisi (Yemeksepeti'nden alınmıştır)
export interface PresetMenuItem {
  name: string;
  description: string;
  price: string;
  image: string;
  imageAlt: string;
  category: 'food' | 'drink';
  subcategory: string;
  stock: null;
}

export const hamurEviMenu: PresetMenuItem[] = [
  // ===== MENÜLER =====
  {
    name: "Nohutlu Pilav Üstü Tavuk Menü",
    description: "Nohutlu Pilav Üstü Tavuk + Ayran (30 cl.)",
    price: "₺350",
    image: "https://images.deliveryhero.io/image/fd-tr/Products/14546410.jpg?width=400&quality=90",
    imageAlt: "Nohutlu Pilav Üstü Tavuk Menü",
    category: "food",
    subcategory: "Menüler",
    stock: null,
  },

  // ===== BAŞLANGIÇLAR =====
  {
    name: "Kıbrıs Badades Patates Kızartması",
    description: "Parmak dilim",
    price: "₺250",
    image: "https://images.deliveryhero.io/image/fd-tr/Products/14546411.jpg?width=400&quality=90",
    imageAlt: "Kıbrıs Badades Patates Kızartması",
    category: "food",
    subcategory: "Başlangıçlar",
    stock: null,
  },
  {
    name: "Bulgur Köftesi",
    description: "2 adet olarak servis edilir.",
    price: "₺200",
    image: "https://images.deliveryhero.io/image/fd-tr/Products/14546412.jpg?width=400&quality=90",
    imageAlt: "Bulgur Köftesi",
    category: "food",
    subcategory: "Başlangıçlar",
    stock: null,
  },

  // ===== BÖREKLER =====
  {
    name: "Hellimli Börek",
    description: "4 adet olarak servis edilir.",
    price: "₺300",
    image: "https://images.deliveryhero.io/image/fd-tr/Products/14546413.jpg?width=400&quality=90",
    imageAlt: "Hellimli Börek",
    category: "food",
    subcategory: "Börekler",
    stock: null,
  },
  {
    name: "Sigara Böreği",
    description: "1 porsiyon / 5 adet",
    price: "₺300",
    image: "https://images.deliveryhero.io/image/fd-tr/Products/14546414.jpg?width=400&quality=90",
    imageAlt: "Sigara Böreği",
    category: "food",
    subcategory: "Börekler",
    stock: null,
  },
  {
    name: "Peynirli Börek",
    description: "4 adet olarak servis edilir.",
    price: "₺300",
    image: "https://images.deliveryhero.io/image/fd-tr/Products/14546415.jpg?width=400&quality=90",
    imageAlt: "Peynirli Börek",
    category: "food",
    subcategory: "Börekler",
    stock: null,
  },

  // ===== GÖZLEMELER =====
  {
    name: "Peynirli Gözleme",
    description: "Özel hamur içerisine peynir eklenerek hazırlanan bir gözleme çeşididir.",
    price: "₺300",
    image: "https://images.deliveryhero.io/image/fd-tr/Products/14546416.jpg?width=400&quality=90",
    imageAlt: "Peynirli Gözleme",
    category: "food",
    subcategory: "Gözlemeler",
    stock: null,
  },
  {
    name: "Hellimli Gözleme",
    description: "Özel hamur içerisine hellim peyniri eklenerek hazırlanan bir gözleme çeşididir.",
    price: "₺300",
    image: "https://images.deliveryhero.io/image/fd-tr/Products/14546417.jpg?width=400&quality=90",
    imageAlt: "Hellimli Gözleme",
    category: "food",
    subcategory: "Gözlemeler",
    stock: null,
  },
  {
    name: "Patatesli Gözleme",
    description: "Özel hamur içerisine patates eklenerek hazırlanan bir gözleme çeşididir.",
    price: "₺300",
    image: "https://images.deliveryhero.io/image/fd-tr/Products/14546418.jpg?width=400&quality=90",
    imageAlt: "Patatesli Gözleme",
    category: "food",
    subcategory: "Gözlemeler",
    stock: null,
  },
  {
    name: "Kaşarlı Gözleme",
    description: "Özel hamur içerisine kaşar peyniri eklenerek hazırlanan bir gözleme çeşididir.",
    price: "₺300",
    image: "https://images.deliveryhero.io/image/fd-tr/Products/14546419.jpg?width=400&quality=90",
    imageAlt: "Kaşarlı Gözleme",
    category: "food",
    subcategory: "Gözlemeler",
    stock: null,
  },
  {
    name: "Patatesli Kaşarlı Gözleme",
    description: "Özel hamur içerisine patates ve kaşar peyniri eklenerek hazırlanan bir gözleme çeşididir.",
    price: "₺300",
    image: "https://images.deliveryhero.io/image/fd-tr/Products/14546420.jpg?width=400&quality=90",
    imageAlt: "Patatesli Kaşarlı Gözleme",
    category: "food",
    subcategory: "Gözlemeler",
    stock: null,
  },
  {
    name: "Hellimli Kaşarlı Gözleme",
    description: "Özel hamur içerisine hellim ve kaşar peyniri eklenerek hazırlanan bir gözleme çeşididir.",
    price: "₺300",
    image: "https://images.deliveryhero.io/image/fd-tr/Products/14546421.jpg?width=400&quality=90",
    imageAlt: "Hellimli Kaşarlı Gözleme",
    category: "food",
    subcategory: "Gözlemeler",
    stock: null,
  },

  // ===== MANTILAR =====
  {
    name: "Çıtır Mantı",
    description: "Yoğurt ve sos ile servis edilir.",
    price: "₺300",
    image: "https://images.deliveryhero.io/image/fd-tr/Products/14546422.jpg?width=400&quality=90",
    imageAlt: "Çıtır Mantı",
    category: "food",
    subcategory: "Mantılar",
    stock: null,
  },
  {
    name: "Kayseri Mantısı",
    description: "Yoğurt ve sos ile servis edilir.",
    price: "₺300",
    image: "https://images.deliveryhero.io/image/fd-tr/Products/14546423.jpg?width=400&quality=90",
    imageAlt: "Kayseri Mantısı",
    category: "food",
    subcategory: "Mantılar",
    stock: null,
  },
  {
    name: "Nonna Mantı",
    description: "Domates sosu ile servis edilir.",
    price: "₺300",
    image: "https://images.deliveryhero.io/image/fd-tr/Products/14546424.jpg?width=400&quality=90",
    imageAlt: "Nonna Mantı",
    category: "food",
    subcategory: "Mantılar",
    stock: null,
  },

  // ===== DÜRÜMLER =====
  {
    name: "Bidda Chicken Wrap",
    description: "Tavuk, marul, domates ve özel sos ile hazırlanan dürüm.",
    price: "₺300",
    image: "https://images.deliveryhero.io/image/fd-tr/Products/14546425.jpg?width=400&quality=90",
    imageAlt: "Bidda Chicken Wrap",
    category: "food",
    subcategory: "Dürümler",
    stock: null,
  },
  {
    name: "Patso Dürüm",
    description: "Patates kızartması, ketçap ve mayonez ile hazırlanan dürüm.",
    price: "₺250",
    image: "https://images.deliveryhero.io/image/fd-tr/Products/14546426.jpg?width=400&quality=90",
    imageAlt: "Patso Dürüm",
    category: "food",
    subcategory: "Dürümler",
    stock: null,
  },
  {
    name: "Bidda Badades Dürüm",
    description: "Patates kızartması, marul, domates ve özel sos ile hazırlanan dürüm.",
    price: "₺250",
    image: "https://images.deliveryhero.io/image/fd-tr/Products/14546427.jpg?width=400&quality=90",
    imageAlt: "Bidda Badades Dürüm",
    category: "food",
    subcategory: "Dürümler",
    stock: null,
  },
  {
    name: "Nonna Dürüm",
    description: "Özel Nonna sosu ve malzemeler ile hazırlanan dürüm.",
    price: "₺300",
    image: "https://images.deliveryhero.io/image/fd-tr/Products/14546428.jpg?width=400&quality=90",
    imageAlt: "Nonna Dürüm",
    category: "food",
    subcategory: "Dürümler",
    stock: null,
  },

  // ===== YAN ÜRÜNLER =====
  {
    name: "Bal & Kaymak",
    description: "Kahvaltılık bal ve kaymak ikilisi.",
    price: "₺150",
    image: "https://images.deliveryhero.io/image/fd-tr/Products/14546429.jpg?width=400&quality=90",
    imageAlt: "Bal & Kaymak",
    category: "food",
    subcategory: "Yan Ürünler",
    stock: null,
  },
  {
    name: "Tereyağı",
    description: "Porsiyon tereyağı.",
    price: "₺100",
    image: "https://images.deliveryhero.io/image/fd-tr/Products/14546430.jpg?width=400&quality=90",
    imageAlt: "Tereyağı",
    category: "food",
    subcategory: "Yan Ürünler",
    stock: null,
  },
  {
    name: "Süzme Yoğurt",
    description: "Porsiyon süzme yoğurt.",
    price: "₺100",
    image: "https://images.deliveryhero.io/image/fd-tr/Products/14546431.jpg?width=400&quality=90",
    imageAlt: "Süzme Yoğurt",
    category: "food",
    subcategory: "Yan Ürünler",
    stock: null,
  },
  {
    name: "Izgara Hellim Peyniri",
    description: "Izgarada pişirilmiş hellim peyniri dilimleri.",
    price: "₺150",
    image: "https://images.deliveryhero.io/image/fd-tr/Products/14546432.jpg?width=400&quality=90",
    imageAlt: "Izgara Hellim Peyniri",
    category: "food",
    subcategory: "Yan Ürünler",
    stock: null,
  },

  // ===== SALATALAR =====
  {
    name: "Izgara Hellimli Salata",
    description: "Mevsim yeşillikleri üzerine ızgara hellim peyniri.",
    price: "₺300",
    image: "https://images.deliveryhero.io/image/fd-tr/Products/14546433.jpg?width=400&quality=90",
    imageAlt: "Izgara Hellimli Salata",
    category: "food",
    subcategory: "Salatalar",
    stock: null,
  },
  {
    name: "Ton Balıklı Salata",
    description: "Mevsim yeşillikleri üzerine ton balığı.",
    price: "₺300",
    image: "https://images.deliveryhero.io/image/fd-tr/Products/14546434.jpg?width=400&quality=90",
    imageAlt: "Ton Balıklı Salata",
    category: "food",
    subcategory: "Salatalar",
    stock: null,
  },
  {
    name: "Izgara Tavuklu Salata",
    description: "Mevsim yeşillikleri üzerine ızgara tavuk dilimleri.",
    price: "₺300",
    image: "https://images.deliveryhero.io/image/fd-tr/Products/14546435.jpg?width=400&quality=90",
    imageAlt: "Izgara Tavuklu Salata",
    category: "food",
    subcategory: "Salatalar",
    stock: null,
  },
  {
    name: "Beyaz Peynirli Salata",
    description: "Mevsim yeşillikleri üzerine beyaz peynir.",
    price: "₺300",
    image: "https://images.deliveryhero.io/image/fd-tr/Products/14546436.jpg?width=400&quality=90",
    imageAlt: "Beyaz Peynirli Salata",
    category: "food",
    subcategory: "Salatalar",
    stock: null,
  },
  {
    name: "Izgara Köfte & Hellim Salata",
    description: "Mevsim yeşillikleri üzerine ızgara köfte ve hellim.",
    price: "₺300",
    image: "https://images.deliveryhero.io/image/fd-tr/Products/14546437.jpg?width=400&quality=90",
    imageAlt: "Izgara Köfte & Hellim Salata",
    category: "food",
    subcategory: "Salatalar",
    stock: null,
  },
  {
    name: "Izgara Köfteli Salata",
    description: "Mevsim yeşillikleri üzerine ızgara köfte.",
    price: "₺300",
    image: "https://images.deliveryhero.io/image/fd-tr/Products/14546438.jpg?width=400&quality=90",
    imageAlt: "Izgara Köfteli Salata",
    category: "food",
    subcategory: "Salatalar",
    stock: null,
  },

  // ===== TATLILAR =====
  {
    name: "Ballı Kaymaklı Katmer",
    description: "Ballı ve kaymaklı çıtır katmer.",
    price: "₺250",
    image: "https://images.deliveryhero.io/image/fd-tr/Products/14546439.jpg?width=400&quality=90",
    imageAlt: "Ballı Kaymaklı Katmer",
    category: "food",
    subcategory: "Tatlılar",
    stock: null,
  },
  {
    name: "Antep Fıstıklı Kaymaklı Katmer",
    description: "Antep fıstığı ve kaymaklı çıtır katmer.",
    price: "₺250",
    image: "https://images.deliveryhero.io/image/fd-tr/Products/14546440.jpg?width=400&quality=90",
    imageAlt: "Antep Fıstıklı Kaymaklı Katmer",
    category: "food",
    subcategory: "Tatlılar",
    stock: null,
  },
  {
    name: "Çikolatalı Katmer",
    description: "Çikolatalı çıtır katmer.",
    price: "₺250",
    image: "https://images.deliveryhero.io/image/fd-tr/Products/14546441.jpg?width=400&quality=90",
    imageAlt: "Çikolatalı Katmer",
    category: "food",
    subcategory: "Tatlılar",
    stock: null,
  },
  {
    name: "Tahin Pekmezli Katmer",
    description: "Tahin ve pekmezli çıtır katmer.",
    price: "₺250",
    image: "https://images.deliveryhero.io/image/fd-tr/Products/14546442.jpg?width=400&quality=90",
    imageAlt: "Tahin Pekmezli Katmer",
    category: "food",
    subcategory: "Tatlılar",
    stock: null,
  },
  {
    name: "Şamişi",
    description: "Geleneksel bir tatlı çeşididir.",
    price: "₺200",
    image: "https://images.deliveryhero.io/image/fd-tr/Products/14546443.jpg?width=400&quality=90",
    imageAlt: "Şamişi",
    category: "food",
    subcategory: "Tatlılar",
    stock: null,
  },

  // ===== İÇECEKLER =====
  {
    name: "Coca-Cola (33 cl.)",
    description: "Kutu içecek",
    price: "₺70",
    image: "https://images.deliveryhero.io/image/fd-tr/Products/14546444.jpg?width=400&quality=90",
    imageAlt: "Coca-Cola",
    category: "drink",
    subcategory: "İçecekler",
    stock: null,
  },
  {
    name: "Fanta (33 cl.)",
    description: "Kutu içecek",
    price: "₺70",
    image: "https://images.deliveryhero.io/image/fd-tr/Products/14546445.jpg?width=400&quality=90",
    imageAlt: "Fanta",
    category: "drink",
    subcategory: "İçecekler",
    stock: null,
  },
  {
    name: "Juss Tea (33 cl.)",
    description: "Kutu içecek",
    price: "₺70",
    image: "https://images.deliveryhero.io/image/fd-tr/Products/14546446.jpg?width=400&quality=90",
    imageAlt: "Juss Tea",
    category: "drink",
    subcategory: "İçecekler",
    stock: null,
  },
  {
    name: "Ayran (30 cl.)",
    description: "Büyük boy",
    price: "₺60",
    image: "https://images.deliveryhero.io/image/fd-tr/Products/14546447.jpg?width=400&quality=90",
    imageAlt: "Ayran",
    category: "drink",
    subcategory: "İçecekler",
    stock: null,
  },
  {
    name: "Meyveli Soda (20 cl.)",
    description: "Cam şişe",
    price: "₺60",
    image: "https://images.deliveryhero.io/image/fd-tr/Products/14546448.jpg?width=400&quality=90",
    imageAlt: "Meyveli Soda",
    category: "drink",
    subcategory: "İçecekler",
    stock: null,
  },
  {
    name: "Coca-Cola Zero Sugar (33 cl.)",
    description: "Kutu içecek",
    price: "₺70",
    image: "https://images.deliveryhero.io/image/fd-tr/Products/14546449.jpg?width=400&quality=90",
    imageAlt: "Coca-Cola Zero Sugar",
    category: "drink",
    subcategory: "İçecekler",
    stock: null,
  },
  {
    name: "Sprite (33 cl.)",
    description: "Kutu içecek",
    price: "₺70",
    image: "https://images.deliveryhero.io/image/fd-tr/Products/14546450.jpg?width=400&quality=90",
    imageAlt: "Sprite",
    category: "drink",
    subcategory: "İçecekler",
    stock: null,
  },
  {
    name: "Sarıyer Gazoz (33 cl.)",
    description: "Kutu içecek",
    price: "₺70",
    image: "https://images.deliveryhero.io/image/fd-tr/Products/14546451.jpg?width=400&quality=90",
    imageAlt: "Sarıyer Gazoz",
    category: "drink",
    subcategory: "İçecekler",
    stock: null,
  },
  {
    name: "Red Bull (25 cl.)",
    description: "Enerji içeceği",
    price: "₺120",
    image: "https://images.deliveryhero.io/image/fd-tr/Products/14546452.jpg?width=400&quality=90",
    imageAlt: "Red Bull",
    category: "drink",
    subcategory: "İçecekler",
    stock: null,
  },
  {
    name: "Su (50 cl.)",
    description: "Pet şişe",
    price: "₺30",
    image: "https://images.deliveryhero.io/image/fd-tr/Products/14546453.jpg?width=400&quality=90",
    imageAlt: "Su",
    category: "drink",
    subcategory: "İçecekler",
    stock: null,
  },
  {
    name: "Soda (20 cl.)",
    description: "Cam şişe",
    price: "₺60",
    image: "https://images.deliveryhero.io/image/fd-tr/Products/14546454.jpg?width=400&quality=90",
    imageAlt: "Soda",
    category: "drink",
    subcategory: "İçecekler",
    stock: null,
  },
  {
    name: "Cappy Pulpy Portakal (30 cl.)",
    description: "Pet şişe",
    price: "₺70",
    image: "https://images.deliveryhero.io/image/fd-tr/Products/14546455.jpg?width=400&quality=90",
    imageAlt: "Cappy Pulpy Portakal",
    category: "drink",
    subcategory: "İçecekler",
    stock: null,
  },
  {
    name: "Ananas Suyu",
    description: "Meyve suyu",
    price: "₺70",
    image: "https://images.deliveryhero.io/image/fd-tr/Products/14546456.jpg?width=400&quality=90",
    imageAlt: "Ananas Suyu",
    category: "drink",
    subcategory: "İçecekler",
    stock: null,
  },
  {
    name: "Karışık Meyve Suyu",
    description: "Meyve suyu",
    price: "₺70",
    image: "https://images.deliveryhero.io/image/fd-tr/Products/14546457.jpg?width=400&quality=90",
    imageAlt: "Karışık Meyve Suyu",
    category: "drink",
    subcategory: "İçecekler",
    stock: null,
  },
  {
    name: "Vişne Suyu",
    description: "Meyve suyu",
    price: "₺70",
    image: "https://images.deliveryhero.io/image/fd-tr/Products/14546458.jpg?width=400&quality=90",
    imageAlt: "Vişne Suyu",
    category: "drink",
    subcategory: "İçecekler",
    stock: null,
  },
  {
    name: "Red Bull Hindistan Cevizi & Açai Aromalı (25 cl.)",
    description: "Enerji içeceği",
    price: "₺120",
    image: "https://images.deliveryhero.io/image/fd-tr/Products/14546459.jpg?width=400&quality=90",
    imageAlt: "Red Bull Hindistan Cevizi & Açai Aromalı",
    category: "drink",
    subcategory: "İçecekler",
    stock: null,
  },
  {
    name: "Red Bull Elma Aromalı (25 cl.)",
    description: "Enerji içeceği",
    price: "₺120",
    image: "https://images.deliveryhero.io/image/fd-tr/Products/14546460.jpg?width=400&quality=90",
    imageAlt: "Red Bull Elma Aromalı",
    category: "drink",
    subcategory: "İçecekler",
    stock: null,
  },
  {
    name: "Red Bull Ahududu Aromalı (25 cl.)",
    description: "Enerji içeceği",
    price: "₺120",
    image: "https://images.deliveryhero.io/image/fd-tr/Products/14546461.jpg?width=400&quality=90",
    imageAlt: "Red Bull Ahududu Aromalı",
    category: "drink",
    subcategory: "İçecekler",
    stock: null,
  },
];
